import { useEffect, useMemo, useState } from 'react';

const sampleFlights = {
  DL567: { airline: 'Delta Air Lines', origin: 'ATL', destination: 'LAX' },
  AA102: { airline: 'American Airlines', origin: 'JFK', destination: 'LAX' },
  UA2184: { airline: 'United Airlines', origin: 'DEN', destination: 'SFO' },
};

function riskLabel(score) {
  if (score >= 75) return 'Critical';
  if (score >= 50) return 'High';
  if (score >= 25) return 'Moderate';
  return 'Low';
}

function fallbackFlightRoute(flightNumber, routes) {
  const normalized = flightNumber.trim().toUpperCase().replace(/\s+/g, '');
  if (sampleFlights[normalized]) return { flightNumber: normalized, ...sampleFlights[normalized], provider: 'sample-route-inference' };
  const usableRoutes = routes.filter(route => route.origin && route.destination);
  const seed = normalized.split('').reduce((sum, char) => sum + char.charCodeAt(0), 0);
  const route = usableRoutes[seed % Math.max(usableRoutes.length, 1)] || { origin: 'ATL', destination: 'LAX' };
  return {
    flightNumber: normalized || 'UNKNOWN',
    airline: normalized.startsWith('DL') ? 'Delta Air Lines' : normalized.startsWith('AA') ? 'American Airlines' : normalized.startsWith('UA') ? 'United Airlines' : 'Unknown airline',
    origin: route.origin,
    destination: route.destination,
    provider: 'sample-route-inference',
  };
}

function buildLocalAssessment(flightNumber, airports, routes) {
  const flight = fallbackFlightRoute(flightNumber, routes);
  const airportByCode = new Map(airports.map(airport => [airport.iata, airport]));
  const origin = airportByCode.get(flight.origin);
  const destination = airportByCode.get(flight.destination);
  if (!origin || !destination) return null;

  const routeExists = routes.some(route => (
    (route.origin === origin.iata && route.destination === destination.iata)
    || (route.origin === destination.iata && route.destination === origin.iata)
  ));
  const hubExposure = Math.max(origin.hubImpactScore || 0, destination.hubImpactScore || 0);
  const delayEnvironment = Math.max(
    origin.departureDelayMinutes || 0,
    origin.arrivalDelayMinutes || 0,
    destination.departureDelayMinutes || 0,
    destination.arrivalDelayMinutes || 0,
  );
  const cancellationEnvironment = Math.max(origin.cancellationRate || 0, destination.cancellationRate || 0);
  const riskScore = Math.round(Math.min(100,
    delayEnvironment * 0.45
    + cancellationEnvironment * 220
    + hubExposure * 0.35
    + (routeExists ? 8 : 14)
    + (origin.groundStop || destination.groundStop ? 25 : 0),
  ));
  const riskLevel = riskLabel(riskScore);

  return {
    flightNumber: flight.flightNumber,
    airline: flight.airline,
    originAirport: origin,
    destinationAirport: destination,
    currentOriginDelay: origin.departureDelayMinutes || 0,
    currentDestinationDelay: destination.arrivalDelayMinutes || 0,
    cancellationEnvironment,
    airportRisk: riskLabel(Math.max(origin.hubImpactScore || 0, destination.hubImpactScore || 0)),
    hubExposure: Number(hubExposure.toFixed(1)),
    estimatedDelayRisk: riskLevel,
    riskScore,
    riskLevel,
    routeExposure: routeExists ? 'Direct route appears in static network' : 'Connection complexity estimated from static network',
    timestamp: new Date().toISOString(),
    disclaimer: 'This is an analytical estimate generated by the Hub Resilience Monitor and is not an official FAA prediction.',
  };
}

async function fetchRisk(apiBaseUrl, flightNumber) {
  if (!apiBaseUrl) throw new Error('Backend URL is not configured');
  const response = await fetch(`${apiBaseUrl}/api/flight-risk/${encodeURIComponent(flightNumber)}`, {
    headers: { Accept: 'application/json' },
  });
  const contentType = response.headers.get('content-type') || '';
  if (!response.ok) throw new Error(`${response.status} ${response.statusText}`);
  if (!contentType.includes('application/json')) throw new Error('Backend did not return JSON');
  return response.json();
}

function AirportRiskCard({ title, airport }) {
  return (
    <div>
      <span>{title}</span>
      <strong>{airport?.iata || '—'}</strong>
      <small>{airport?.name}</small>
      <small>Departure {airport?.departureDelayMinutes || 0} min · Arrival {airport?.arrivalDelayMinutes || 0} min</small>
    </div>
  );
}

export default function FlightRiskAnalyzer({ airports, routes, sourceMode, apiBaseUrl }) {
  const [flightNumber, setFlightNumber] = useState('DL567');
  const [assessment, setAssessment] = useState(() => buildLocalAssessment('DL567', airports, routes));
  const [message, setMessage] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const sampleList = useMemo(() => Object.keys(sampleFlights), []);

  useEffect(() => {
    if (!assessment && airports.length) {
      setAssessment(buildLocalAssessment(flightNumber, airports, routes));
    }
  }, [airports, routes, assessment, flightNumber]);

  async function analyzeFlight(event) {
    event.preventDefault();
    const normalized = flightNumber.trim().toUpperCase().replace(/\s+/g, '');
    if (!normalized) return;
    setIsLoading(true);
    setMessage('');
    try {
      const liveAssessment = await fetchRisk(apiBaseUrl, normalized);
      setAssessment(liveAssessment);
      setMessage(sourceMode === 'live' ? 'Backend flight-risk endpoint connected.' : 'Backend connected, but source data may be sample mode.');
    } catch (error) {
      const localAssessment = buildLocalAssessment(normalized, airports, routes);
      setAssessment(localAssessment);
      setMessage(`Using local analytical fallback for ${normalized}: ${error.message}`);
    } finally {
      setIsLoading(false);
    }
  }

  return (
    <section className="flight-risk-page">
      <div className="card flight-risk-intro">
        <span className="section-kicker">Operational flight-delay risk</span>
        <h2>Flight Risk Checker</h2>
        <p>
          Enter a flight number to translate current airport delay conditions, cancellation environment, hub exposure,
          and route-network complexity into an estimated risk class.
        </p>
        <p className="panel-footnote">
          This does not claim exact prediction certainty and is not an official FAA prediction.
        </p>
      </div>

      <div className="dashboard-grid flight-risk-grid">
        <form className="card risk-form" aria-label="Flight risk checker" onSubmit={analyzeFlight}>
          <div className="section-heading">
            <div>
              <span className="section-kicker">Flight input</span>
              <h2>Check a Flight</h2>
            </div>
          </div>
          <label className="risk-field">
            <span>Flight Number</span>
            <input
              value={flightNumber}
              onChange={event => setFlightNumber(event.target.value.toUpperCase())}
              placeholder="DL567, AA102, UA2184"
            />
          </label>
          <button className="methodology-button risk-submit" type="submit" disabled={isLoading}>
            {isLoading ? 'Analyzing...' : 'Analyze Risk'}
          </button>
          <div className="sample-flight-row">
            {sampleList.map(sample => (
              <button key={sample} type="button" onClick={() => setFlightNumber(sample)}>{sample}</button>
            ))}
          </div>
          {message && <p className="panel-footnote">{message}</p>}
        </form>

        <div className="card risk-output">
          <div className="section-heading">
            <div>
              <span className="section-kicker">Output</span>
              <h2>Flight Risk Assessment</h2>
            </div>
            {assessment && <span className={`risk-level risk-${assessment.riskLevel.toLowerCase()}`}>{assessment.riskLevel}</span>}
          </div>

          {assessment ? (
            <>
              <div className="risk-summary-grid">
                <div><span>Flight</span><strong>{assessment.flightNumber}</strong><small>{assessment.airline}</small></div>
                <AirportRiskCard title="Origin Airport" airport={assessment.originAirport} />
                <AirportRiskCard title="Destination Airport" airport={assessment.destinationAirport} />
                <div><span>Estimated Delay Risk</span><strong>{assessment.riskScore} / 100</strong><small>{assessment.estimatedDelayRisk}</small></div>
              </div>

              <div className="risk-meter" aria-label={`Risk score ${assessment.riskScore} out of 100`}>
                <i style={{ width: `${assessment.riskScore}%` }} />
              </div>

              <div className="risk-details-grid">
                <div>
                  <h3>Risk Factors</h3>
                  <ul className="risk-factors">
                    <li>Current Origin Delay: {assessment.currentOriginDelay || 0} minutes</li>
                    <li>Current Destination Delay: {assessment.currentDestinationDelay || 0} minutes</li>
                    <li>Cancellation Environment: {((assessment.cancellationEnvironment || 0) * 100).toFixed(1)}%</li>
                    <li>Airport Risk: {assessment.airportRisk}</li>
                    <li>Hub Exposure: {assessment.hubExposure}</li>
                    <li>{assessment.routeExposure}</li>
                  </ul>
                </div>
                <div className="risk-recommendation">
                  <h3>Recommendation</h3>
                  <p>
                    {assessment.riskLevel === 'Critical' || assessment.riskLevel === 'High'
                      ? 'Monitor airline departure status closely and consider backup options if travel is time-sensitive.'
                      : assessment.riskLevel === 'Moderate'
                        ? 'Keep monitoring airport conditions and leave extra buffer time.'
                        : 'No major airport-level risk signals are visible right now. Continue normal travel monitoring.'}
                  </p>
                  <small>{assessment.disclaimer}</small>
                </div>
              </div>
            </>
          ) : (
            <p className="no-data">Enter a flight number to calculate risk.</p>
          )}
        </div>
      </div>
    </section>
  );
}
